logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

spring:
  threads:
    virtual:
      enabled: true
  profiles:
    active: mongodb
  endpoint:
    health:
      show-details: always
